# Generated by Django 5.0.7 on 2024-10-10 00:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rawg_id', models.IntegerField(unique=True)),
                ('bg_image', models.CharField(blank=True, max_length=255, null=True)),
                ('tba', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('rating_top', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ratings_count', models.IntegerField(default=0)),
                ('reviews_text_count', models.IntegerField(default=0)),
                ('released', models.DateField(blank=True, null=True)),
                ('metacritic', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('playtime', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('esrb_rating', models.CharField(blank=True, max_length=30, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('platforms', models.ManyToManyField(blank=True, to='platforms.platforms')),
            ],
        ),
    ]
