# Generated by Django 5.0.7 on 2024-10-10 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_requirements', models.TextField(blank=True, null=True)),
                ('recommended_requirements', models.TextField(blank=True, null=True)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.games')),
                ('platform', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platforms')),
            ],
        ),
    ]
