# Generated by Django 5.0.7 on 2024-10-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        ('platforms', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='game',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='platform',
        ),
        migrations.AddField(
            model_name='requirements',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to='games.games'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='platform',
            field=models.ManyToManyField(blank=True, null=True, to='platforms.platforms'),
        ),
    ]
